#!/usr/bin/env python3
"""
Generates pipeline_documentation.txt — a complete, human-readable breakdown
of every stage in the Belgrade Group Recommender pipeline:

  1. Event Extraction Pipeline  (raw tags → type_hints, price, noise, city)
  2. User Preference Parsing Pipeline  (LLM prompt + JSON schema)
  3. Retrieval Pipeline  (cosine search + hard filters)
  4. Ranking Pipeline  (soft score + least-misery group aggregation)

No model calls are made — this is purely documentation generation.
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent
_SRC  = _ROOT / "src"
if _SRC.is_dir() and str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

OUT = _ROOT / "pipeline_documentation.txt"

W = 84
SEP  = "=" * W
THIN = "-" * W
SEC  = "#" * W


def box(title: str) -> str:
    pad = (W - len(title) - 4) // 2
    return f"\n{SEP}\n  {' ' * pad}{title}\n{SEP}"


def sub(title: str) -> str:
    return f"\n{THIN}\n  {title}\n{THIN}"


def write_doc() -> None:
    lines: list[str] = []

    lines += [
        SEP,
        "  BELGRADE GROUP RECOMMENDER — COMPLETE PIPELINE DOCUMENTATION",
        "  Generated automatically from source code",
        SEP,
        "",
        "  This file documents every algorithm, prompt, and decision rule in the pipeline.",
        "  Two main sub-pipelines:",
        "",
        "    A. EVENT EXTRACTION PIPELINE",
        "       Converts raw Telegram event posts into structured EventAttributes.",
        "       Input:  NormalizedEvent (description text + raw hashtags)",
        "       Output: EventAttributes (type_hints, noise, free/paid, city, price)",
        "",
        "    B. USER PREFERENCE PARSING PIPELINE",
        "       Converts free-text user requests into structured ParsedUserPreferences.",
        "       Input:  plain-text user query (Serbian / Russian / English)",
        "       Output: ParsedUserPreferences (liked_types, noise, hard constraints)",
        "",
        "    Then: RETRIEVAL → HARD FILTERING → RANKING",
        SEP,
    ]

    # =========================================================================
    # A. EVENT EXTRACTION PIPELINE
    # =========================================================================
    lines.append(box("A. EVENT EXTRACTION PIPELINE"))
    lines += [
        "",
        "  Entry point:  extract_event_attributes_maybe_lazy_gemini(event)",
        "  Source file:  src/belgrade_recommender/extract/attributes.py",
        "",
        "  Two modes:",
        "    1. RULES-ONLY  (default, always runs)",
        "       Pure deterministic logic. No API calls, no latency.",
        "    2. RULES + LAZY GEMINI  (optional, env-flag gated)",
        "       If USE_LAZY_GEMINI_EVENT_ATTRIBUTES=1 AND rules produced noise=unknown,",
        "       Gemini is called to enrich noise/outdoor/type_hints.",
        "       Rule-based price and city signals always take priority over Gemini.",
        "",
    ]

    # ── A1: Tag → type_hints mapping ─────────────────────────────────────────
    lines.append(sub("A1 — HASHTAG → TYPE_HINTS MAPPING  (_TAG_TO_TYPES)"))
    lines += [
        "",
        "  ALGORITHM:",
        "    For each raw hashtag on the event:",
        "      1. Normalize: lowercase → strip '#' → strip spaces and hyphens",
        "      2. Look up in _TAG_TO_TYPES dict",
        "      3. Append matched snake_case type tokens (deduped)",
        "",
        "  _type_hints_from_tags() source:",
        "    def _type_hints_from_tags(tags: list[str]) -> list[str]:",
        "        out, seen = [], set()",
        "        for raw in tags:",
        "            key = raw.lower().replace('#','').replace(' ','').replace('-','')",
        "            for hint in _TAG_TO_TYPES.get(key, []):",
        "                if hint not in seen:",
        "                    seen.add(hint); out.append(hint)",
        "        return out",
        "",
        "  FULL _TAG_TO_TYPES DICTIONARY (hashtag → [type_hint, ...]):",
        "",
        "  ── LIVE MUSIC ──────────────────────────────────────────────────────",
        "  livemusic           → [live_music]",
        "  liveperformance     → [live_music, concert]",
        "  livemusicfestival   → [live_music, festival]",
        "  concert             → [concert, live_music]",
        "  freeconcert         → [concert, live_music]",
        "  music               → [live_music]",
        "  musicevent          → [live_music]",
        "  musicfestival       → [festival, live_music]",
        "  performance         → [concert, live_music]",
        "  performanceart      → [concert, exhibition]",
        "  openmic             → [open_mic, live_music]",
        "  jamsession          → [open_mic, live_music]",
        "",
        "  ── GENRE TAGS ──────────────────────────────────────────────────────",
        "  jazz                → [jazz, live_music]",
        "  jazzfestival        → [jazz, festival, live_music]",
        "  jazzclub            → [jazz, live_music]",
        "  jazznight           → [jazz, live_music, bar]",
        "  swing               → [jazz, live_music]",
        "  bebop               → [jazz, live_music]",
        "  blues               → [blues, live_music]",
        "  bluesmusic          → [blues, live_music]",
        "  classicalmusic      → [classical_music, concert]",
        "  opera               → [classical_music, concert]",
        "  philharmonic        → [philharmonic, classical_music, concert]",
        "  symphony            → [classical_music, concert]",
        "  chambermusic        → [chamber_music, classical_music, concert]",
        "  rock / rockmusic    → [concert, live_music]",
        "  indiemusic          → [concert, live_music]",
        "  alternativemusic    → [concert, live_music]",
        "  folk / folkmusic    → [folk_traditional, live_music]",
        "  worldmusic          → [world_music, live_music]",
        "  afrobeat            → [world_music, live_music]",
        "  reggae              → [world_music, live_music]",
        "  soul / rnb          → [soul, live_music]",
        "  hiphop / rap        → [hip_hop, concert]",
        "  hiphopfestival      → [hip_hop, festival, live_music]",
        "  electronic          → [electronic, nightlife]",
        "  techno              → [techno, nightlife]",
        "  darktechno          → [dark_techno, techno, nightlife]",
        "  darkelectronic      → [dark_ambient, nightlife]",
        "  darkambient         → [dark_ambient, nightlife]",
        "  industrial /        → [dark_ambient, nightlife]",
        "  industrialmusic",
        "  ebm / darkwave      → [dark_ambient, nightlife]",
        "  gothic / goth       → [gothic, dark_ambient]",
        "  gothicmusic         → [gothic, dark_ambient, nightlife]",
        "  metal / heavymetal  → [concert, live_music]",
        "  avantgarde          → [concert, live_music]",
        "  acoustic            → [acoustic, live_music]",
        "  singersongwriter    → [singer_songwriter, acoustic, live_music]",
        "  djset / dj          → [electronic, nightlife]",
        "  vinyl               → [vinyl_music, bar]",
        "  vinylmarket         → [vinyl_music, market]",
        "",
        "  ── NIGHTLIFE / CLUB ────────────────────────────────────────────────",
        "  nightlife           → [nightlife]",
        "  party               → [party, nightlife]",
        "  clubbing            → [nightlife, club]",
        "  nightclub           → [nightlife, club]",
        "  rave                → [nightlife, techno]",
        "  clubnight           → [nightlife, club]",
        "",
        "  ── ART / EXHIBITION ────────────────────────────────────────────────",
        "  artexhibition /     → [exhibition]",
        "  exhibition / art",
        "  contemporaryart     → [exhibition]",
        "  streetart           → [street_art, exhibition]",
        "  photography         → [photography, exhibition]",
        "  design              → [design, exhibition]",
        "  architecture        → [architecture]",
        "  culture             → [culture]",
        "",
        "  ── MUSEUM / HISTORY ────────────────────────────────────────────────",
        "  museum              → [museum]",
        "  history             → [history]",
        "  historicaltour      → [guided_tour, history]",
        "",
        "  ── FILM / CINEMA ───────────────────────────────────────────────────",
        "  film / filmfestival → [film] / [film, festival]",
        "  filmscreening       → [film]",
        "  cinema              → [film]",
        "  documentary         → [film]",
        "",
        "  ── THEATRE / COMEDY ────────────────────────────────────────────────",
        "  theatre / theater   → [theatre]",
        "  standupcomedy       → [comedy]",
        "  improvtheatre       → [comedy, theatre]",
        "",
        "  ── FOOD & DRINK ────────────────────────────────────────────────────",
        "  foodfestival        → [food_festival, food]",
        "  food / gastronomy   → [food]",
        "  restaurant          → [restaurant]",
        "  streetfood          → [food, outdoor]",
        "  farmersmarket       → [food, market, outdoor]",
        "  winetasting         → [wine, bar]",
        "  cocktails           → [cocktail_bar, bar]",
        "  craftbeer           → [craft_beer, bar]",
        "  specialtycoffee     → [cafe]",
        "  asiancuisine        → [asian_cuisine, restaurant]",
        "  serbianfood         → [serbian_cuisine, restaurant]",
        "  brunch              → [food, cafe]",
        "",
        "  ── BAR / CAFE ──────────────────────────────────────────────────────",
        "  bar                 → [bar]",
        "  cafe                → [cafe]",
        "  speakeasy           → [speakeasy, bar]",
        "  rooftop / rooftopbar→ [rooftop_bar, bar]",
        "  kafana              → [kafana, folk_traditional]",
        "  kafananight         → [kafana, folk_traditional, nightlife]",
        "  rakija              → [folk_traditional, kafana]",
        "  lounge              → [lounge, bar]",
        "  latenightbar        → [late_night_bar, bar]",
        "  bookbar             → [bar, lecture]",
        "  splav / splavovi    → [splav, nightlife, bar]",
        "  riverbar            → [splav, bar]",
        "  waterfront          → [waterfront]",
        "",
        "  ── OUTDOOR / NATURE ────────────────────────────────────────────────",
        "  hiking / hikingtrip → [hiking, outdoor]",
        "  excursion           → [excursion, outdoor]",
        "  outdoor             → [outdoor]",
        "  nature              → [outdoor, nature]",
        "  openair             → [outdoor]",
        "  sports / fitness    → [sport] / [sport, outdoor]",
        "  yoga / running /    → [outdoor, sport]",
        "  cycling",
        "  camping             → [outdoor, nature]",
        "  bushcraft           → [bushcraft, outdoor, nature]",
        "  dance / dancing     → [dance, nightlife]",
        "  meditation          → [meditation]",
        "",
        "  ── FAMILY ──────────────────────────────────────────────────────────",
        "  familyfun /         → [family_friendly]",
        "  familyfriendly /",
        "  kidsactivities",
        "",
        "  ── EDUCATION / LECTURE ─────────────────────────────────────────────",
        "  lecture             → [lecture]",
        "  workshop            → [workshop]",
        "  science / astronomy → [lecture]",
        "  bookclub /          → [lecture, social]",
        "  bookdiscussion",
        "  tech / technology   → [tech_meetup]",
        "  startup             → [tech_meetup, networking]",
        "",
        "  ── SOCIAL / NETWORKING ─────────────────────────────────────────────",
        "  networking          → [networking]",
        "  communityevent      → [social]",
        "  languageexchange    → [language_exchange, social]",
        "  gaming              → [gaming]",
        "  anime / manga       → [anime]",
        "  cosplay             → [cosplay, anime]",
        "  kpop                → [kpop]",
        "  quiznight / trivia  → [quiz, bar]",
        "  boardgame/s         → [board_game, cafe]",
        "  tabletop / dnd /rpg → [board_game]",
        "",
        "  ── ESOTERIC ────────────────────────────────────────────────────────",
        "  tarot / occult /    → [esoteric]",
        "  esoteric / crystal /",
        "  pagan / witchcraft /",
        "  astrology",
        "  spirituality        → [esoteric, meditation]",
        "",
        "  ── DIETARY / LIFESTYLE ─────────────────────────────────────────────",
        "  vegan / vegetarian  → [vegan]",
        "  veganfood           → [vegan, food]",
        "  veganfestival       → [vegan, food_festival, festival]",
        "  plantbased          → [vegan]",
        "  glutenfree          → [gluten_free]",
        "  organic             → [organic, food]",
        "  rawvegan            → [raw_vegan, vegan]",
        "  nonalcoholic /      → [non_alcoholic, bar]",
        "  mocktail/s",
        "  zeroalcohol         → [non_alcoholic]",
        "",
        "  ── MARKET / CRAFT ──────────────────────────────────────────────────",
        "  craftfair /         → [craft_fair, market]",
        "  craftmarket",
        "  market / fleamarket → [market]",
        "  festival (general)  → [festival]",
        "",
    ]

    # ── A2: Keyword scan ──────────────────────────────────────────────────────
    lines.append(sub("A2 — DESCRIPTION KEYWORD SCAN  (_kw_map)"))
    lines += [
        "",
        "  ALGORITHM:",
        "    After tag-based extraction, scan event description text (lowercased)",
        "    for keywords that hashtags might have missed.",
        "    Each keyword is a substring match; no word-boundary enforcement unless",
        "    the keyword is a full phrase (e.g. 'classical music' prevents matching",
        "    bare 'classical' in 'classical architecture').",
        "",
        "  Source code:",
        "    seen = set(type_hints)   # don't duplicate what tags already produced",
        "    for kw, label in _kw_map:",
        "        if kw in text_lower and label not in seen:",
        "            type_hints.append(label)",
        "            seen.add(label)",
        "",
        "  FULL _kw_map (keyword → type_hint):",
        "",
        "  'jazz'              → jazz",
        "  'bebop'             → jazz",
        "  'swing music'       → jazz        (phrase-only, avoids 'swingset' etc.)",
        "  'swing jazz'        → jazz",
        "  'swing dance'       → jazz",
        "  'philharmonic'      → philharmonic",
        "  'symphony'          → classical_music",
        "  'classical music'   → classical_music  (phrase-only, NOT bare 'classical')",
        "  'chamber music'     → chamber_music",
        "  'hiking'            → hiking",
        "  'exhibition'        → exhibition",
        "  'lecture'           → lecture",
        "  'workshop'          → workshop",
        "  'concert'           → concert",
        "  'restaurant'        → restaurant",
        "  'photography'       → photography",
        "  'gallery'           → exhibition",
        "  'festival'          → festival",
        "  'opera'             → classical_music",
        "  'film'              → film",
        "  'cinema'            → film",
        "  'comedy'            → comedy",
        "  'theatre' / 'theater' → theatre",
        "  'networking'        → networking",
        "  'startup'           → tech_meetup",
        "  'craft beer'        → craft_beer",
        "  'wine'              → wine",
        "  'cocktail'          → cocktail_bar",
        "  'rooftop'           → rooftop_bar",
        "  'speakeasy'         → speakeasy",
        "  'vinyl'             → vinyl_music",
        "  'open mic' / 'open-mic' → open_mic",
        "  'family'            → family_friendly",
        "  'kids' / 'children' → family_friendly",
        "  'street art'        → street_art",
        "  'kafana'            → kafana",
        "  'grill' / 'rostilj' → grill",
        "  'dance'             → dance",
        "  'meditation' / 'meditacija' → meditation",
        "  'lounge'            → lounge",
        "  'language exchange' → language_exchange",
        "  'asian cuisine'     → asian_cuisine",
        "  'sushi' / 'ramen'   → asian_cuisine",
        "  'serbian cuisine'   → serbian_cuisine",
        "  'srpska kuhinja'    → serbian_cuisine",
        "  'rakija'            → folk_traditional",
        "  'hip hop' / 'hip-hop' / 'rap music' → hip_hop",
        "  'vegan'             → vegan",
        "  'plant-based'       → vegan",
        "  'gluten-free' / 'gluten free' → gluten_free",
        "  'tarot' / 'occult'  → esoteric",
        "  'splav'             → splav",
        "  'board game/s'      → board_game",
        "  'tabletop'          → board_game",
        "  'bubble tea'        → asian_cuisine",
        "  'cosplay'           → cosplay",
        "  'book club'         → social",
        "  'brutalism'         → architecture",
        "  'architectural tour' → architecture",
        "  'manga'             → anime",
        "",
        "  NOTE: 'techno' was intentionally REMOVED from _kw_map.",
        "  Reason: 'technology', 'biotech', 'tech meetup' all contain 'techno' as",
        "  a substring, causing false-positive nightlife tags on tech events.",
        "  Techno events are caught via #techno hashtag in _TAG_TO_TYPES instead.",
        "",
    ]

    # ── A3: Noise hint ────────────────────────────────────────────────────────
    lines.append(sub("A3 — NOISE LEVEL HINT  (_noise_hint_from_types)"))
    lines += [
        "",
        "  ALGORITHM:",
        "    1. Check type_hints set against three frozen sets (in priority order):",
        "       HIGH   → if any hint ∈ NOISY_TYPE_HINTS",
        "       LOW    → elif any hint ∈ QUIET_TYPE_HINTS",
        "       MED_HI → elif any hint ∈ MEDIUM_HIGH_HINTS",
        "    2. If no match: fall back to raw tag scan for common signal words.",
        "    3. If still no match: return 'unknown'.",
        "",
        "  _NOISY_TYPE_HINTS (→ noise=high):",
        "    techno, dark_techno, electronic, nightlife, party, club,",
        "    hip_hop, dark_ambient, gothic, rave",
        "",
        "  _QUIET_TYPE_HINTS (→ noise=low):",
        "    lecture, exhibition, museum, classical_music,",
        "    workshop, film, theatre, esoteric, meditation",
        "",
        "  _MEDIUM_HIGH_HINTS (→ noise=medium_high):",
        "    live_music, concert, jazz, blues, folk_traditional,",
        "    open_mic, world_music, soul, singer_songwriter",
        "",
        "  Raw tag fallback (used only when all type_hints miss):",
        "    HIGH : techno, rave, openair, nightlife, party, livemusic",
        "    LOW  : lecture, exhibition, museum, classicalmusic, workshop",
        "",
    ]

    # ── A4: Price / free detection ────────────────────────────────────────────
    lines.append(sub("A4 — FREE / PRICE DETECTION  (rules.py + tag scan)"))
    lines += [
        "",
        "  TWO-STAGE free detection:",
        "",
        "  Stage 1 — Regex on description text (detect_free_entry):",
        "    Pattern: r'\\b(free\\s+entry|free\\s+admission|no\\s+cover|",
        "                 besplat(?:an|ni|an)?|ulaz\\s+je\\s+slobodan|",
        "                 вход\\s+свободн|бесплатн)\\b'",
        "    Matches: 'free entry', 'free admission', 'no cover', 'besplatan',",
        "             'ulaz je slobodan', 'вход свободный', 'бесплатно'",
        "",
        "  Stage 2 — Raw tag scan (if Stage 1 missed):",
        "    Normalize each tag: lowercase → strip # → strip spaces/hyphens",
        "    Match against: {freeevent, freeadmission, freeentry, freeconcert,",
        "                    freeconcerts, freetickets, freeaccess, noadmission}",
        "    If any tag matches → price_free_signal = True",
        "",
        "  PAID DETECTION (paid_language_hint):",
        "    Regex: 'tickets? from', 'ticket price', 'from N RSD/EUR/€'",
        "    OR any standalone 'N RSD' / 'N EUR' / 'N €' amount in text",
        "    Result: price_paid_signal = True (overridden if free=True)",
        "",
        "  PRICE AMOUNT EXTRACTION:",
        "    RSD: pattern r'(\\d[\\d\\s\\.,]*)\\s*(?:RSD|rsd|дин\\.?|din\\.?)\\b'",
        "         → max_rsd_amount() returns the largest RSD value found",
        "    EUR: pattern r'(\\d[\\d\\s\\.,]*)\\s*(?:EUR|eur|€|euros?)\\b'",
        "         → max_eur_amount() returns the largest EUR value found",
        "",
    ]

    # ── A5: Outdoor hint ──────────────────────────────────────────────────────
    lines.append(sub("A5 — OUTDOOR HINT"))
    lines += [
        "",
        "  ALGORITHM:",
        "    1. Normalize all tags to lowercase, strip '#'",
        "    2. IF any tag ∈ {hiking, outdoor, excursion, nature, openair,",
        "                     trekking, outdooradventure, outdooractivities,",
        "                     watersports, kayaking, camping}",
        "       OR 'outdoor' / 'open-air' / 'napolju' in description text",
        "       → outdoor_hint = True",
        "    3. ELIF any tag ∈ {museum, exhibition, lecture, cinema, theatre, theater}",
        "       AND no outdoor tag present → outdoor_hint = False",
        "    4. Otherwise → outdoor_hint = None  (unknown)",
        "",
    ]

    # ── A6: City hint ─────────────────────────────────────────────────────────
    lines.append(sub("A6 — CITY HINT  (detect_city_hint)"))
    lines += [
        "",
        "  ALGORITHM (substring match on full text, lowercased):",
        "    'novi sad' / 'нови сад' / 'petrovaradin'  → 'novi_sad'",
        "    'belgrade' / 'beograd' / 'белград'         → 'belgrade'",
        "    'serbia' / 'srbij' / 'серб'                → 'serbia_other'",
        "    (none of the above)                         → 'unknown'",
        "",
    ]

    # ── A7: Gemini lazy enrichment ────────────────────────────────────────────
    lines.append(sub("A7 — OPTIONAL GEMINI LAZY ENRICHMENT"))
    lines += [
        "",
        "  Activation: USE_LAZY_GEMINI_EVENT_ATTRIBUTES=1 in environment",
        "              AND rules produced noise_level_hint='unknown'",
        "",
        "  When activated: calls Gemini with EVENT_ATTRIBUTES_LLM_INSTRUCTION prompt.",
        "  Merge strategy (rules always win for price/city):",
        "    noise_level_hint : Gemini (if ≠ unknown), else rules",
        "    outdoor_hint     : Gemini (if not None), else rules",
        "    city_hint        : Gemini (if rules='unknown'), else rules",
        "    type_hints       : union(rules, gemini) deduplicated, max 12",
        "    date_snippets    : union(rules, gemini) deduplicated, max 5",
        "",
        "  FULL GEMINI EVENT ATTRIBUTES PROMPT:",
        "  (EVENT_ATTRIBUTES_LLM_INSTRUCTION in prompts.py)",
        "",
    ]

    # embed the actual prompt
    try:
        from belgrade_recommender.llm.prompts import EVENT_ATTRIBUTES_LLM_INSTRUCTION
        for pl in EVENT_ATTRIBUTES_LLM_INSTRUCTION.splitlines():
            lines.append(f"    {pl}")
    except ImportError:
        lines.append("    [could not import prompt — run from project root]")

    lines.append("")

    # =========================================================================
    # B. USER PREFERENCE PARSING PIPELINE
    # =========================================================================
    lines.append(box("B. USER PREFERENCE PARSING PIPELINE"))
    lines += [
        "",
        "  Entry point:  parse_preferences_plain_text(text)",
        "  Source file:  src/belgrade_recommender/llm/gemini_preferences.py",
        "",
        "  Input:   plain-text user request (any language: SR/RU/EN/Cyrillic)",
        "  Model:   Gemini (default: gemini-2.0-flash, override via GEMINI_MODEL env)",
        "  Output:  ParsedUserPreferences  (structured JSON, validated by Pydantic)",
        "",
        "  API CALL STRUCTURE:",
        "    system_instruction = PREFERENCE_SYSTEM_INSTRUCTION",
        "    response_mime_type = 'application/json'",
        "    response_schema    = ParsedUserPreferences   (Pydantic model)",
        "    user message       = 'User preference text:\\n{text}\\n\\nExtract structured fields as JSON.'",
        "",
    ]

    lines.append(sub("B1 — FULL SYSTEM PROMPT  (PREFERENCE_SYSTEM_INSTRUCTION)"))
    lines.append("")
    try:
        from belgrade_recommender.llm.prompts import PREFERENCE_SYSTEM_INSTRUCTION
        for pl in PREFERENCE_SYSTEM_INSTRUCTION.splitlines():
            lines.append(f"    {pl}")
    except ImportError:
        lines.append("    [could not import prompt]")
    lines.append("")

    lines.append(sub("B2 — OUTPUT SCHEMA  (ParsedUserPreferences)"))
    lines += [
        "",
        "  Pydantic model: src/belgrade_recommender/schemas/parsed_preferences.py",
        "",
        "  ParsedUserPreferences",
        "  ├── summary_one_line: str          (one-line English summary)",
        "  ├── hard_constraints: ParsedHardConstraints",
        "  │   ├── must_be_free: bool | None",
        "  │   ├── budget_max_rsd: int | None",
        "  │   ├── must_be_free_or_under_budget: bool | None",
        "  │   ├── forbidden_event_categories: list[str]",
        "  │   ├── preferred_days_of_week: list[str]",
        "  │   ├── earliest_start_hour_weekday: int | None",
        "  │   ├── preferred_time_windows: list[str]",
        "  │   ├── venue_requirements: list[str]    (smoke_free, non_alcoholic, pet_friendly)",
        "  │   ├── dietary_restrictions: list[str]  (vegan, gluten_free, nut_free, ...)",
        "  │   └── city: str | None",
        "  └── soft_preferences: ParsedSoftPreferences",
        "      ├── liked_types: list[str]     (snake_case event type tags, 2–5)",
        "      └── noise_tolerance: NoiseLevel",
        "          Enum: low | medium | medium_high | high | unknown",
        "",
        "  KEY FIELD RULES (from the prompt):",
        "",
        "  liked_types:",
        "    - Short snake_case tags inferring what the user wants to DO or EXPERIENCE",
        "    - No abstract quality words (fun, nice, authentic alone)",
        "    - No constraint words (free, cheap → use hard_constraints instead)",
        "    - No dietary words (vegan, gluten_free → use dietary_restrictions)",
        "    - Examples: jazz, live_music, craft_beer, board_game, dark_ambient",
        "",
        "  must_be_free:",
        "    - ONLY when explicitly stated: 'besplatno', 'free', 'džabe', 'бесплатно'",
        "    - 'jeftino' or 'mali budzet' → use budget_max_rsd, NOT must_be_free",
        "",
        "  noise_tolerance:",
        "    low      : 'hocu da pricam', 'tiho', 'mirno', 'ne preglasno', meditacija",
        "    medium   : restaurant dinner, team outing, casual social",
        "    medium_high: jazz bar, open mic, folk concert (live music but not a club)",
        "    high     : 'zurka', 'techno', 'rave', 'sto glasnije', nightclub",
        "    RULE: 'ne preglasno' ALWAYS → low (hard cap, never medium_high/high)",
        "",
        "  forbidden_event_categories:",
        "    - ONLY when user explicitly rejects: 'ne volim X', 'mrzim X', 'bez X'",
        "    - NEVER for dietary/noise preferences",
        "    - NEVER for things user is searching FOR",
        "",
    ]

    # =========================================================================
    # C. RETRIEVAL PIPELINE
    # =========================================================================
    lines.append(box("C. RETRIEVAL PIPELINE"))
    lines += [
        "",
        "  Source files:",
        "    src/belgrade_recommender/retrieve/cosine_search.py",
        "    src/belgrade_recommender/retrieve/hard_filters.py",
        "    src/belgrade_recommender/retrieve/encoder.py",
        "",
    ]

    lines.append(sub("C1 — SEMANTIC EMBEDDING + COSINE SEARCH"))
    lines += [
        "",
        "  Encoder: SentenceEncoder (sentence-transformers)",
        "  Model:   paraphrase-multilingual-MiniLM-L12-v2  (384-dim, multilingual)",
        "           Supports Serbian, Russian, English natively.",
        "",
        "  CORPUS ENCODING (one-time at startup):",
        "    texts = [build_embedding_text(event) for event in indexable_events]",
        "    corpus_matrix = encoder.encode(texts)   # shape: (N_events, 384)",
        "    Rows are L2-normalized for dot-product = cosine similarity.",
        "",
        "  build_embedding_text(event) combines:",
        "    event_description_resolved + ' ' + ' '.join(event.tags)",
        "",
        "  QUERY ENCODING (per group, ~instant after corpus is warm):",
        "    joint_query = '\\n\\n'.join(member['query'] for member in group)",
        "    query_vec   = encoder.encode([joint_query])[0]   # shape: (384,)",
        "",
        "  cosine_top_k SOURCE CODE:",
        "    def cosine_top_k(corpus, query, k):",
        "        scores = corpus @ query        # dot product → cosine (L2-normalized)",
        "        order  = np.argsort(-scores)[:k]",
        "        return [(int(i), float(scores[i])) for i in order]",
        "",
        "    k = 80  (retrieve top-80 semantic candidates before hard filtering)",
        "",
    ]

    lines.append(sub("C2 — HARD FILTERING  (passes_all_hard_constraints)"))
    lines += [
        "",
        "  GROUP RULE: event must satisfy EVERY member's hard constraints.",
        "    passes_all_hard_constraints = all(passes_hard_constraints(h, ev, attrs)",
        "                                      for h in hards)",
        "",
        "  passes_hard_constraints() checks in order:",
        "",
        "  1. CITY FILTER (_city_ok):",
        "     If member prefers 'belgrade' → reject events with city_hint='novi_sad'",
        "     'belgrade_or_daytrip_serbia' or 'serbia_other' → always pass",
        "",
        "  2. FREE / BUDGET FILTER (_free_and_budget_ok):",
        "     must_be_free=True — benefit-of-the-doubt logic:",
        "       PASS  if price_free_signal=True            (explicit free signal)",
        "       FAIL  if price_paid_signal=True            (explicit paid signal)",
        "       FAIL  if price_amount_rsd or price_amount_eur is set",
        "       PASS  if no price info at all              (ambiguous → allow through)",
        "     Rationale: most informal Telegram events carry no price tag at all.",
        "     Blocking them would shrink the free-seeker candidate pool to near zero.",
        "     must_be_free_or_under_budget + budget_max_rsd:",
        "       FAIL  if price_amount_rsd > cap",
        "       FAIL  if price_amount_eur * 120 > cap  (EUR→RSD approx conversion)",
        "",
        "  3. FORBIDDEN CATEGORIES (_forbidden_categories_ok):",
        "     For each token in forbidden_event_categories:",
        "       Normalize: lowercase, strip",
        "       FAIL if token is a substring of any raw tag  (or vice versa)",
        "       FAIL if token is a substring of any type_hint (or vice versa)",
        "       Substring both directions: 'techno' blocks 'darktechno'; 'rave' blocks 'rave'",
        "",
        "  4. DAY OF WEEK FILTER (_day_of_week_ok):",
        "     If preferred_days_of_week is set AND event has day_of_week_hints:",
        "       FAIL if the sets don't intersect",
        "       If event has no day hints → PASS (undated events aren't excluded)",
        "",
        "  5. VENUE REQUIREMENTS (_venue_requirements_ok):",
        "     smoke_free    → FAIL if event tags/hints contain {smoking, smoking_area, pusacka}",
        "     pet_friendly  → FAIL if tags contain {no_pets, no_dogs, pets_not_allowed}",
        "",
        "  6. DIETARY RESTRICTIONS (_dietary_restrictions_ok):",
        "     gluten_free   → FAIL if tags contain {gluten, breaded, pasta_only}",
        "     nut_free      → FAIL if tags contain {nut_bar, peanut_heavy}",
        "",
        "  After hard filtering: keep up to 20 candidates for ranking.",
        "",
        "  PRE-FILTER: NON-EVENT CONTENT EXCLUSION (_is_non_event)",
        "    Applied BEFORE hard constraints. Removes promotional posts, ads, and",
        "    B2B service announcements that are not attendable events.",
        "",
        "    Two-signal approach (threshold: 2+ hits to exclude):",
        "",
        "    A. Description text patterns (regex, case-insensitive):",
        "       'event agency/agencies', 'event planning'",
        "       'organizing a/the corporate/company' (broader: organizing|organiz+ing)",
        "       'for sale', 'free delivery', 'order now', 'shop now'",
        "       'discount offer', 'contact us to order', 'NN% off'",
        "       'home textiles/decor/delivery'",
        "",
        "    B. Raw hashtag scan (each matching tag counts as one hit):",
        "       #eventagency, #eventplanning, #eventmanagement, #eventorganizer",
        "       #corporateevent, #corporateparty, #forsale, #forrent",
        "       #homedelivery, #deliveryservice, #shopnow, #ordernow",
        "",
        "    Requiring 2 hits prevents false positives from legitimate events that",
        "    happen to mention 'order' or 'corporate' in passing.",
        "",
    ]

    # =========================================================================
    # D. RANKING PIPELINE
    # =========================================================================
    lines.append(box("D. RANKING PIPELINE"))
    lines += [
        "",
        "  Source files:",
        "    src/belgrade_recommender/rank/soft_score.py",
        "    src/belgrade_recommender/rank/group_rank.py",
        "",
    ]

    lines.append(sub("D1 — PER-MEMBER SOFT SCORE  (soft_adjusted_score)"))
    lines += [
        "",
        "  For each (event, member_prefs) pair, compute a score in [0.0, 1.0].",
        "  Four-stage pipeline: squash → bonus → mismatch penalty → noise penalty.",
        "",
        "  STAGE 1 — SOFT SQUASH  (threshold = 0.40)",
        "    Addresses the cosine-similarity trap: in dense 384-dim embedding spaces,",
        "    unrelated events still score ~0.35–0.45 due to vector space density.",
        "    Solution: quadratically compress any base score below the margin.",
        "",
        "    if base < 0.40:",
        "        base = base² / 0.40",
        "",
        "    Effect on representative scores:",
        "      sem=0.40 → 0.40 (unchanged, at boundary)",
        "      sem=0.35 → 0.31 (mild compression)",
        "      sem=0.30 → 0.23 (moderate compression)",
        "      sem=0.20 → 0.10 (heavy compression)",
        "    Scores ≥ 0.40 are untouched — preserves ranking of meaningful matches.",
        "",
        "  STAGE 2 — LIKED-TYPE BONUS",
        "    liked  = [t.lower() for t in prefs.soft_preferences.liked_types]",
        "    th_set = {t.lower() for t in event.tags}",
        "            | {h.lower() for h in attrs.type_hints}",
        "",
        "    matched_count = count of liked where any(lt in x or x in lt for x in th_set)",
        "    bonus = min(matched_count × 0.06, 0.28)   # +6% per match, max +28%",
        "",
        "  STAGE 3 — ACTIVE MISMATCH PENALTY  (-0.10)",
        "    Fires only when ALL of these are true:",
        "      a) User has at least one liked_type",
        "      b) Event has at least one type_hint",
        "      c) matched_count == 0  (zero overlap — confirmed type mismatch)",
        "",
        "    This is distinct from 'no bonus' (passive): it is an active deduction",
        "    for confirmed misfit. Events with empty type_hints are not penalised",
        "    (we lack data, so we stay neutral).",
        "",
        "  STAGE 4 — NOISE MISMATCH PENALTY",
        "    noise = prefs.soft_preferences.noise_tolerance",
        "    if noise in ('low','unknown') and attrs.noise_level_hint == 'high':",
        "        penalty += 0.12            # -12%: quiet user, loud event",
        "    if noise == 'low' and attrs.noise_level_hint == 'medium':",
        "        penalty += 0.04            # -4%: quiet user, medium event",
        "",
        "  LIKED_TYPE MATCHING RULE:",
        "    Substring match in BOTH directions:",
        "      lt='jazz'    matches type_hint='jazz'       ✓",
        "      lt='music'   matches type_hint='live_music' ✓  (music ⊂ live_music)",
        "      lt='outdoor' matches tag='outdoorevents'    ✓  (outdoor ⊂ outdoorevents)",
        "",
    ]

    lines.append(sub("D2 — GROUP AGGREGATION  (rank_by_least_misery)"))
    lines += [
        "",
        "  ALGORITHM:",
        "    For each candidate event:",
        "      1. Compute soft_adjusted_score for EACH member",
        "      2. min_soft  = min(all member scores)   ← least-misery criterion",
        "      3. mean_soft = mean(all member scores)",
        "",
        "    Sort descending by: (min_soft, mean_soft)",
        "    Primary key = min_soft  → protect the member who'd be least happy",
        "    Tiebreaker  = mean_soft → prefer events the whole group enjoys more",
        "",
        "  DEDUPLICATION (after sorting):",
        "    Recurring Telegram series post the same event every month with only the",
        "    month/year changed in the title (e.g. 'Free concerts in Belgrade in June',",
        "    '... in May', '... in October'). Without dedup, the entire top-10 fills",
        "    with the same event series.",
        "",
        "    Dedup key: strip month names + 4-digit years from the description, then",
        "    take the first 60 lowercased characters of the result.",
        "    Only the highest-ranked entry for each key is kept.",
        "",
        "  WHY LEAST MISERY?",
        "    A group recommendation must work for EVERYONE, not just the majority.",
        "    Least misery prevents a 5-person group from recommending a techno rave",
        "    just because 4 people would enjoy it if the 5th person hates loud music.",
        "",
    ]

    # =========================================================================
    # E. FULL PIPELINE FLOW SUMMARY
    # =========================================================================
    lines.append(box("E. FULL PIPELINE FLOW — END TO END"))
    lines += [
        "",
        "  ┌─────────────────────────────────────────────────────────────────────┐",
        "  │  INPUT: group of members, each with a plain-text preference query   │",
        "  └─────────────────────────────────────────────────────────────────────┘",
        "                             │",
        "                  ┌──────────▼──────────┐",
        "                  │  B. USER PREF PARSE  │  Gemini structured JSON output",
        "                  │  (per member)        │  → ParsedUserPreferences",
        "                  └──────────┬──────────┘",
        "                             │",
        "  ┌──────────────────────────▼──────────────────────────────────────────┐",
        "  │  Corpus (6948 events, pre-encoded at startup, L2-normalized 384-dim) │",
        "  └──────────────────────────┬──────────────────────────────────────────┘",
        "                             │",
        "                  ┌──────────▼──────────┐",
        "                  │  C1. COSINE SEARCH   │  joint query → top-80 candidates",
        "                  └──────────┬──────────┘",
        "                             │",
        "                  ┌──────────▼──────────┐",
        "                  │  A.  EVENT ATTRS     │  rules + optional Gemini lazy",
        "                  │  (per candidate)     │  → type_hints, noise, free, city",
        "                  └──────────┬──────────┘",
        "                             │",
        "                  ┌──────────▼──────────┐",
        "                  │  C2. HARD FILTERS    │  group intersection of all",
        "                  │  (all members must   │  member hard constraints",
        "                  │   pass)              │  → keep up to 20 candidates",
        "                  └──────────┬──────────┘",
        "                             │",
        "                  ┌──────────▼──────────┐",
        "                  │  D1. SOFT SCORE      │  per member: base(sem) + bonus",
        "                  │  (per member)        │  - penalty (noise mismatch)",
        "                  └──────────┬──────────┘",
        "                             │",
        "                  ┌──────────▼──────────┐",
        "                  │  D2. LEAST MISERY    │  sort by (min_soft, mean_soft)",
        "                  │  GROUP RANK          │  → top-10 recommendations",
        "                  └──────────┬──────────┘",
        "                             │",
        "  ┌──────────────────────────▼──────────────────────────────────────────┐",
        "  │  OUTPUT: ranked list of events with scores, tags, attrs per member  │",
        "  └─────────────────────────────────────────────────────────────────────┘",
        "",
        SEP,
        "  SCORE FORMULA SUMMARY:",
        THIN,
        "  semantic_score  = cosine_similarity(joint_query_embedding, event_embedding)",
        "                    [0.0 – 1.0, from multilingual MiniLM-L12-v2]",
        "",
        "  base            = semantic_score",
        "                    → if base < 0.40: base = base² / 0.40   (soft squash)",
        "",
        "  soft_score(m,e) = clamp(",
        "                      base",
        "                      + 0.06 × matched_liked_types         (max +0.28)",
        "                      - 0.10 × [liked≥1 & hints≥1 & match=0]  (mismatch)",
        "                      - 0.12 × [noise=low & event=high]",
        "                      - 0.04 × [noise=low & event=medium]",
        "                    , 0, 1)",
        "",
        "  group_score(e)  = (min(soft_score for all members),",
        "                     mean(soft_score for all members))   # tuple, sort desc",
        SEP,
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {OUT}")
    print(f"  Lines : {len(lines)}")
    print(f"  Size  : {OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    write_doc()
